WebUIAutoTest/src/web/app/main/forms.py
# coding=utf-8

from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, SelectField
from wtforms.validators import DataRequired, Regexp, ValidationError


def required_when_send_mail(form, field):
    if (form.send_email.data == 'true') and (not field.data):
        raise ValidationError('当发送邮件时，此项不能为空')


def required_when_dingding_enable(form, field):
    if (form.notifier_enable.data == 'true') and (not field.data):
        raise ValidationError('当启动钉钉通知时，此项不能为空')


def required_when_dbtype_selected(dbtype):
    def _required_when_dbtype_selected(form, field):
        if dbtype == 'oracle' and (form.dbtype.data == 'oracle') and (not field.data):
            raise ValidationError('当选择Oracle数据库时，此项不能为空')
        elif dbtype == 'mysql'and (form.dbtype.data == 'mysql') and (not field.data):
            raise ValidationError('当选择MySql数据库时，此项不能为空')
    return _required_when_dbtype_selected


def required_when_extension_ui_enable(form, field):
    if (form.extension_ui_enable.data == 'true') and (not field.data):
        raise ValidationError('当启动启用ui拓展时，此项不能为空')


class RunningConfigForm(FlaskForm):
    # [PROJECT] [TEST] [LOG]
    browser_type = SelectField(label='运行浏览器类型',
                               choices=[('chrome', '谷歌浏览器'), ('firefox', '火狐浏览器'), ('360', '360浏览器')],
                               render_kw={})
    browser_path_360 = StringField(label='360浏览器安装路径',
                                   validators=[DataRequired(message="路径不能为空")],
                                   render_kw={})
    timeout = StringField(label='隐形等待时间',
                          validators=[Regexp(regex=r'^\d+$', message='只能输入正整数'), DataRequired(message='隐形等待时间不能为空')],
                          render_kw={})
    headless = SelectField(label='是否采用无头模式',
                           choices=[('false', '否'), ('true', '是')],
                           render_kw={})
    skip_test_method = SelectField(label='发生错误或失败时跳过之后的案例',
                                   choices=[('false', '否'), ('true', '是')],
                                   render_kw={})
    extension_ui_enable = SelectField(label='是否启用ui拓展',
                                      choices=[('false', '否'), ('true', '是')],
                                      render_kw={})
    extension_ui_module_name = StringField(label='指定拓展的ui类路径',
                                           validators=[required_when_extension_ui_enable],
                                           render_kw={})
    logging_level = SelectField(label='日志输出级别(只读)',
                                choices=[('debug', 'Debug'),
                                         ('info', 'Info'),
                                         ('warning', 'Warning'),
                                         ('error', 'Error')],
                                render_kw={})
    manage_case_type = SelectField(label='组织管理用例方式(只读)',
                                   choices=[('json', 'Json'),
                                            ('excel', 'Excel')],
                                   render_kw={})

    # [EMAIL]
    send_email = SelectField(label='是否发送邮件',
                             choices=[('true', '是'), ('false', '否')],
                             render_kw={})
    gen_report = SelectField(label='是否生成报告',
                             choices=[('true', '是'), ('false', '否')],
                             render_kw={})
    smtp_server_address = StringField(label='SMTP服务器地址',
                                      validators=[required_when_send_mail],
                                      render_kw={})
    smtp_port = StringField(label='SMTP服务器地址端口',
                            validators=[required_when_send_mail, Regexp(regex=r'^\d+$', message='只能输入正整数')],
                            render_kw={})
    smtp_tls = SelectField(label='使用STARTTLS加密',
                           choices=[('true', '是'), ('false', '否')],
                           render_kw={})
    smtp_ssl = SelectField(label='SSL/TLS',
                           choices=[('true', '是'), ('false', '否')],
                           render_kw={})
    smtp_login_name = StringField(label='SMTP服务器登录名',
                                  validators=[required_when_send_mail],
                                  render_kw={})
    smtp_login_passwd = PasswordField(label='SMTP服务器登录密码',
                                      validators=[required_when_send_mail],
                                      render_kw={})
    sender_address = StringField(label='发件地址',
                                 validators=[required_when_send_mail],
                                 render_kw={})
    receiver_address = StringField(label='收件地址',
                                   validators=[required_when_send_mail],
                                   render_kw={})
    email_title = StringField(label='邮件主题',
                              validators=[required_when_send_mail],
                              render_kw={})
    email_text = StringField(label='正文内容',
                             validators=[required_when_send_mail],
                             render_kw={})

    # [REPORT] [NOTIFIER]
    title = StringField(label='报告标题',
                        validators=[DataRequired(message='报告标题不能为空')],
                        render_kw={})
    description = StringField(label='报告描述',
                              validators=[DataRequired(message='报告描述不能为空')],
                              render_kw={})
    notifier_enable = SelectField(label='是否启用钉钉通知',
                                  choices=[('true', '是'), ('false', '否')],
                                  render_kw={})
    access_token = StringField(label='钉钉机器人access_token',
                               validators=[required_when_dingding_enable],
                               render_kw={})
    is_at_all = SelectField(label='是否@所有人',
                            choices=[('true', '是'), ('false', '否')],
                            render_kw={})
    at_mobiles = StringField(label='@一个或多个成员(使用手机号，多个手机号使用逗号分隔)',
                             validators=[],
                             render_kw={})

    # [DATABASE] [ORACLE] [MYSQL]
    dbtype = SelectField(label='数据库类型',
                         choices=[('oracle', 'Oracle'), ('mysql', 'MySql')],
                         render_kw={})
    dsn_oracle = StringField(label='DSN(DataBase Server Name)',
                             validators=[required_when_dbtype_selected(dbtype='oracle')],
                             render_kw={})
    user_oracle = StringField(label='用户名',
                              validators=[required_when_dbtype_selected(dbtype='oracle')],
                              render_kw={})
    passwd_oracle = PasswordField(label='密码',
                                  validators=[required_when_dbtype_selected(dbtype='oracle')],
                                  render_kw={})
    host_mysql = StringField(label='主机名或IP地址',
                             validators=[required_when_dbtype_selected(dbtype='mysql')],
                             render_kw={})
    user_mysql = StringField(label='用户名',
                             validators=[required_when_dbtype_selected(dbtype='mysql')],
                             render_kw={})
    passwd_mysql = PasswordField(label='密码',
                                 validators=[required_when_dbtype_selected(dbtype='mysql')],
                                 render_kw={})
    port_mysql = StringField(label='端口',
                             validators=[required_when_dbtype_selected(dbtype='mysql')],
                             render_kw={})
    charset_mysql = StringField(label='编码',
                                validators=[required_when_dbtype_selected(dbtype='mysql')],
                                render_kw={})

    submit = SubmitField('提交')


class WebConfigForm(FlaskForm):
    theme_type = SelectField(label='主题选择',
                             choices=[
                                 ('default', 'default'),
                                 ('paper', 'paper'),
                                 ('flatly', 'flatly'),
                                 ('journal', 'journal'),
                                 ('lumen', 'lumen'),
                                 ('yeti', 'yeti'),
                             ],
                             render_kw={})
    submit = SubmitField('保存')

WebUIAutoTest/src/web/app/config/__init__.py
# coding=utf-8

"""
Author: zhangzheng
Description: 
Version: 0.0.1
LastUpdateDate: 
UpadteURL: 
LOG: 
"""

WebUIAutoTest/src/web/app/main/__init__.py
# coding=utf-8

from flask import Blueprint

bp = Blueprint("main", __name__)

from src.web.app.main import routes

WebUIAutoTest/src/web/app/main/routes.py
# coding=utf-8

from flask import render_template, jsonify, current_app, request, abort
from flask_login import current_user
from datetime import datetime
import os

from src.web.app.main import bp
from src.web.app.extensions import db, cache
from src.web.app.models import BuildInfo
from src.web.app.util.util import exception_handle, save_request_session_info

from src.config.config import Config as ProjectConfig
from src.public.public import Public

@bp.before_app_request
def before_request():
    if current_user.is_authenticated:
        current_user.last_seen = datetime.now()
        db.session.commit()


@bp.route("/")
@bp.route("/index")
# @cache.cached(timeout=60 * 60)
def index():
    return render_template("main/index.html", title="主页")


@bp.route('/index/get_build_count', methods=['POST'])
def get_build_count():
    form_flag = request.form.get('flag', None)
    if form_flag is None:
        return jsonify({
            'error_no': -1,
            'error_msg': '缺少参数flag',
        })
    elif form_flag == 'current':
        user_id = current_user.id
    elif form_flag == 'all':
        user_id = None
    else:
        return jsonify({
            'error_no': -1,
            'error_msg': '参数flag传入非法值',
        })
    try:
        data = BuildInfo.get_last_30_days_build_counts(user_id=user_id)
    except Exception as e:
        exception_handle(current_app, e)
        return jsonify({
            'error_no': -1,
            'error_msg': '错误信息 [' + str(e.args) + ']',
        })
    else:
        return jsonify({
            'error_no': 0,
            'error_msg': '',
            'data': data,
        })


@bp.route('/cover')
def cover():
    return render_template('main/cover.html')


@bp.route('/upload', methods=['POST'])
def upload():
    if request.method == 'POST':
        file = request.files.get('file', None)
        form_type = request.form.get('type', None)

        if file is None:
            return jsonify({
                'error_no': -1,
                'error_msg': '未找到上传文件',
            })

        if form_type is None:
            return jsonify({
                'error_no': -1,
                'error_msg': '缺少type参数',
            })

        if form_type == 'case':
            try:
                cases_dir_name = 'TestCases'
                cases_zip_name = 'TestCases.zip'
                file_path = os.path.join(ProjectConfig.project_dir, cases_zip_name)
                file.save(file_path)
                # 每次解压前先备份原案例
                if os.path.exists(file_path):
                    os.rename(
                        os.path.join(ProjectConfig.project_dir, cases_dir_name),
                        os.path.join(ProjectConfig.project_dir, cases_dir_name + '_bk_' + datetime.now().strftime("%Y%m%d_%H%M%S"))
                    )
                Public.unpack_archive(file_path, ProjectConfig.project_dir)
            except Exception as e:
                exception_handle(current_app, e)
                return jsonify({
                    'error_no': -1,
                    'error_msg': '错误信息 [' + str(e.args) + ']',
                })
            else:
                return jsonify({
                    'error_no': 0,
                    'error_msg': '',
                })
        else:
            return jsonify({
                'error_no': -1,
                'error_msg': '参数type传入非法值',
            })
    else:
        abort(405)


# 注册其他路由
import src.web.app.main.config_routes
import src.web.app.main.editor_routes
import src.web.app.main.execution_routes
import src.web.app.main.reports_routes
import src.web.app.main.logs_routes
import src.web.app.main.coder_routes

WebUIAutoTest/src/web/app/templates/main/_upload.html
<form action="{{ url_for('main.upload') }}" method="post" class="dropzone" id="myDropzone" enctype="multipart/form-data"></form>

WebUIAutoTest/src/web/app/templates/main/coder.html
{% extends "base.html" %}

{% block app_content %}
    <div class="container-fluid">
        <div class="panel panel-default">
            <div class="panel-heading">{{ file_name }}</div>
            <div class="panel-body" id="container" style="height: 0px; padding-bottom: 45%"></div>
            <div id="code-content" style="display: none">{{ code_content }}</div>
            <br>
            <div class="panel-footer" style="padding-bottom: 40px;">
                <p class="pull-left" style="padding-top: 5px;">操作</p>
                <div class="btn-toolbar" role="toolbar" style="float: right;">
                    <div class="btn-group" role="group">
                        <button id="save-code" type="button" class="btn btn-primary">保存</button>
                    </div>
                    <div class="btn-group" role="group">
                        <button id="download-code" type="button" class="btn btn-default">下载</button>
                    </div>
                </div>
           </div>
        </div>
    </div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{url_for('static', filename='js/plugins/monaco-editor/min/vs/loader.js')}}"></script>
    <script src="{{url_for('static', filename='js/plugins/download/download.js')}}"></script>
    <script src="{{url_for('static', filename='js/main/coder.js')}}"></script>
    <script type="text/javascript">
        var codeContent = document.getElementById('code-content').textContent;
        var filePath = "{{ file_path }}";
        var fileName = "{{ file_name }}";
    </script>
{% endblock %}

WebUIAutoTest/src/web/app/templates/main/config.html
{% extends "base.html" %}
{% import "bootstrap/wtf.html" as wtf %}


{% block styles %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/plugins/bootstrap-table/bootstrap-table.min.css') }}" rel="stylesheet">
{% endblock styles %}

{% block body_attribs %}
data-spy="scroll" data-target="#myScrollspy" data-offset="150" style="position: relative"
{% endblock %}

{% block app_content %}

<div class="container-fluid">
    <div class="row">
        <nav class="col-md-3" id="myScrollspy">
            <ul class="nav nav-pills nav-stacked" style="position: fixed">
                <li class="active"><a href="#exec">用例执行</a></li>
                <li><a href="#email">邮件相关</a></li>
                <li><a href="#report">报告与通知</a></li>
                <li class="dropdown">
                    <a class="dropdown-toggle" data-toggle="dropdown" href="database">数据库<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#database-oracle">Oracle</a></li>
                        <li><a href="#database-mysql">MySql</a></li>
                    </ul>
                </li>
                <li><a href="#"><span class="glyphicon glyphicon-arrow-up">顶部</span></a></li>
            </ul>
        </nav>

    <form method="post" action="" novalidate>
        {{ form.hidden_tag() }}
        <div class="col-md-9">
             <div id="exec">
                <h1>用例执行</h1>
                 {{wtf.form_field(form.browser_type)}}
                 {{wtf.form_field(form.browser_path_360)}}
                 {{wtf.form_field(form.timeout)}}
                 {{wtf.form_field(form.headless)}}
                 {{wtf.form_field(form.skip_test_method)}}
                 {{wtf.form_field(form.extension_ui_enable)}}
                 {{wtf.form_field(form.extension_ui_module_name)}}
                 {{wtf.form_field(form.logging_level, disabled="none")}}
                 {{wtf.form_field(form.manage_case_type, disabled="none")}}
             </div>
            <div id="email">
                <h1>邮件相关</h1>
                {{wtf.form_field(form.send_email)}}
                {{wtf.form_field(form.gen_report)}}
                {{wtf.form_field(form.smtp_server_address)}}
                {{wtf.form_field(form.smtp_port)}}
                {{wtf.form_field(form.smtp_ssl)}}
                {{wtf.form_field(form.smtp_tls)}}
                {{wtf.form_field(form.smtp_login_name)}}
                {{wtf.form_field(form.smtp_login_passwd, data_toggle="password")}}
                {{wtf.form_field(form.sender_address)}}
                {{wtf.form_field(form.receiver_address)}}
                {{wtf.form_field(form.email_title)}}
                {{wtf.form_field(form.email_text)}}
                <label>责任人信息登记</label>
                <div id="toolbar" class="btn-group">
                    <button id="table-responsible-info-btn-add" type="button" class="btn btn-default">
                        <span class="glyphicon glyphicon-plus"></span>新增
                    </button>
                    <button id="table-responsible-info-btn-edit" type="button" class="btn btn-default">
                        <span class="glyphicon glyphicon-pencil"></span>修改
                    </button>
                    <button id="table-responsible-info-btn-delete" type="button" class="btn btn-default">
                        <span class="glyphicon glyphicon-remove"></span>删除
                    </button>
                    <button id="table-responsible-info-btn-save" type="button" class="btn btn-default">
                        <span class="glyphicon glyphicon-save"></span>保存责任人信息
                    </button>
                </div>
                <table id="table-responsible-info"></table>
            </div>
            <div id="report">
                <h1>报告与通知</h1>
                {{wtf.form_field(form.title)}}
                {{wtf.form_field(form.description)}}
                {{wtf.form_field(form.notifier_enable)}}
                {{wtf.form_field(form.access_token)}}
                {{wtf.form_field(form.is_at_all)}}
                {{wtf.form_field(form.at_mobiles)}}
            </div>
            <div id="database">
                <h1>数据库</h1>
                {{wtf.form_field(form.dbtype)}}
            </div>
            <div id="database-oracle">
                <h3>Oracle</h3>
                {{wtf.form_field(form.dsn_oracle)}}
                {{wtf.form_field(form.user_oracle)}}
                {{wtf.form_field(form.passwd_oracle, data_toggle="password")}}
            </div>
            <div id="database-mysql">
                <h3>MySql</h3>
                {{wtf.form_field(form.host_mysql)}}
                {{wtf.form_field(form.user_mysql)}}
                {{wtf.form_field(form.passwd_mysql, data_toggle="password")}}
                {{wtf.form_field(form.port_mysql)}}
                {{wtf.form_field(form.charset_mysql)}}
            </div>
                <!--{{ wtf.form_field(form.submit, class="btn btn-primary", onclick="sendForm()") }}-->
                {{ wtf.form_field(form.submit, class="btn btn-primary") }}
            </div>
        </form>
    </div>
    <div class="row">
        <br>
    </div>
</div>

<div class="modal fade" id="table-responsible-add-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">添加姓名与邮箱</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label for="add-responsible-name" class="control-label">姓名:</label>
                        <input type="text" class="form-control" id="add-responsible-name">
                    </div>
                    <div class="form-group">
                        <label for="add-responsible-email-address" class="control-label">邮箱地址:</label>
                        <input type="text" class="form-control" id="add-responsible-email-address">
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" id="table-responsible-add-modal-add-button">添加</button>
            </div>
        </div>
    </div>
</div>
<div class="modal fade" id="table-responsible-edit-modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">修改姓名与邮箱</h4>
            </div>
            <div class="modal-body">
                <form>
                <div class="form-group">
                    <label for="edit-responsible-name" class="control-label">姓名:</label>
                    <input type="text" class="form-control" id="edit-responsible-name">
                </div>
                <div class="form-group">
                    <label for="edit-responsible-email-address" class="control-label">邮箱地址:</label>
                    <input type="text" class="form-control" id="edit-responsible-email-address">
                </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" id="table-responsible-edit-modal-edit-button">修改</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    {{ super() }}
    <script src="{{url_for('static', filename='js/main/config.js')}}"></script>
    <script src="{{url_for('static', filename='js/plugins/bootstrap-table/bootstrap-table.min.js')}}"></script>
    <script src="{{url_for('static', filename='js/plugins/bootstrap-table/bootstrap-table-locale-all.min.js')}}"></script>
{% endblock %}

WebUIAutoTest/src/web/app/templates/main/cover.html
{% extends "base.html" %}

<!--{% block app_content %}-->


<!--{% endblock %}-->

{% block head %}
    {{ super() }}
    <link href="{{ url_for('static', filename='css/main/cover.css') }}" rel="stylesheet">
{% endblock %}

{% block navbar %}
{% endblock %}

{% block content %}
    <div class="site-wrapper">
      <div class="site-wrapper-inner">
        <div class="cover-container">
          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand">WebUI自动化测试</h3>
              <nav>
                <ul class="nav masthead-nav">
                    <li class="active"><a href="{{ url_for('main.index') }}">主页</a></li>
                    {% if not current_user.is_authenticated %}
                    <li><a href="{{ url_for('auth.login') }}">登录</a></li>
                    <li><a href="{{ url_for('auth.email_authentication') }}">注册</a></li>
                    {% else %}
                    <li><a href="{{ url_for('auth.logout') }}">退出</a></li>
                    {% endif %}
                </ul>
              </nav>
            </div>
          </div>
          <div class="inner cover">
            <h1 class="cover-heading">欢迎使用WebUIAutoTest.</h1>
            <p class="lead">您可以在此方便管理案例、构建自动化测试、查看运行结果.</p>
            <p class="lead">
              <a href="{{ url_for('main.index') }}" class="btn btn-lg btn-default">进入主页</a>
            </p>
          </div>
          <div class="mastfoot">
            <div class="inner">
              <p>Version {{ version }} For <a href="https://gitee.com/azhengzz/WebUIAutoTest">WebUIAutoTest</a>, by <a href="https://gitee.com/azhengzz">@azhengzz</a>.</p>
            </div>
          </div>
        </div>
      </div>
    </div>
{% endblock %}

WebUIAutoTest/src/web/app/templates/main/editor.html
{% extends "base.html" %}

{% block styles %}
    {{ super() }}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/plugins/zTree_v3/zTreeStyle/zTreeStyle.css') }}"  type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/plugins/bootstrap-select/bootstrap-select.min.css') }}"  type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/plugins/dropzone/dropzone.min.css') }}"  type="text/css">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/main/editor.css') }}"  type="text/css">
{% endblock %}


{% block app_content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-lg-3">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>案例目录</strong></h3>
                </div>
                <div class="panel-body pre-scrollable" style="height: 0px; padding-bottom: 150%">
                    <ul id="treeCase" class="ztree" style="-moz-user-select: none;"></ul>
                </div>
                <div class="panel-footer">
                    <button id="upload" type="button" class="btn btn-default" onclick="upload()" >上传</button>
                </div>
            </div>
        </div>
        <div class="col-lg-4">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>执行计划</strong></h3>
                </div>
                <div id="treePlan-div" class="panel-body pre-scrollable" style="height: 0px; padding-bottom: 110%">
                    <ul id="treePlan" class="ztree" build-hash="" style="-moz-user-select: none;"></ul>
                </div>
            </div>
        </div>
        <div class="col-lg-3">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>构建计划</strong></h3>
                </div>
                <div class="panel-body pre-scrollable" style="height: 0px; padding-bottom: 150%">
                    <ul id="treeBuild" class="ztree" style="-moz-user-select: none;"></ul>
                </div>
                <div class="panel-footer">
                    <small id="exec-plan-name"></small><small>绑定责任人信息：</small><br>
                    <small id="responsible-info"></small>
                </div>
            </div>
        </div>
        <div class="col-lg-2">
            <div class="panel panel-info">
                <div class="panel-heading">
                    <h3 class="panel-title"><strong>编辑操作</strong></h3>
                </div>
                <div class="panel-body pre-scrollable" style="height: 0px; padding-bottom: 239%">
                    <h5>保存执行计划</h5>
                    <p><button id="save-plan" type="button" class="btn btn-default" onclick="savePlan()">保存</button></p>
                    <div id="tips" class="well well-lg">
                        <small>提示：</small>
                        <li><small>只有保存勾选状态下的执行计划和构建计划才可以执行</small></li>
                        <li><small>执行计划中存在例如</small><small style="text-decoration: line-through; font-style: italic"> demo.py </small><small>则表示该节点已被修改(可能是目录、文件、类或方法)，这时可以手工将其删除后再从左侧重新添加</small></li>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="exec-plan-responsible-edit-modal" build-hash="" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">设置执行计划对应的责任人</h4>
            </div>
            <div class="modal-body">
                <form>
                    <div class="form-group">
                        <label class="control-label">选择对应的责任人:</label><small id="responsible-select-loading" style="color: #d50617">(正在加载责任人信息...)</small>
                        <select multiple class="selectpicker form-control" id="exec-plan-responsible-edit-modal-select">
                        </select>
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary" id="exec-plan-responsible-edit-modal-edit-button">确定</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="upload-modal" build-hash="" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">上传测试用例</h4>
            </div>
            <div class="modal-body">
                <small style="color: #d50617">只支持上传TestCases目录的压缩文件, 原目录将会被替换(备份到同级目录下)</small>
                {% include "main/_upload.html" %}
            </div>
        </div>
    </div>
</div>

{% endblock %}


{% block scripts %}
    {{ super() }}
    <script type="text/javascript" src="{{ url_for('static', filename='js/plugins/zTree_v3/jquery.ztree.core.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/plugins/zTree_v3/jquery.ztree.excheck.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/plugins/zTree_v3/jquery.ztree.exedit.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/plugins/bootstrap-select/bootstrap-select.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/main/editor.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/plugins/dropzone/dropzone.min.js') }}"></script>
{% endblock %}